spring:
  application:
    name: productApi

  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  health:
    redis:
      enabled: true