spring:
  application:
    name: product-api

  profiles:
    active: dev

  config:
    import: optional:configserver:https://localhost:8888

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: env, health, info, circuitbreakers, circuitbreakerevents
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true





